name: 'Hello world'
description: 'testing actions'
author: 'ion'

inputs:
  envs:
    description: 'envs'
    required: true
    default: ''

# Define your outputs here.
outputs:
  vars:
    description: 'the vars'

runs:
  using: node20
  main: dist/index.js