name: "Use env"
on:
  workflow_dispatch:

jobs:
  use-env:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Setup variables based on branch
        id: get_vars
        uses: ./use-env
        with:
          branch: "dev"
          envs: |
            [
              {
                "branch": "demo",
                "VAR_X": "aaaa-demo",
                "VAR_Y": 42
              },
              {
                "branch": "dev",
                "VAR_X": "bbbb-dev",
                "VAR_Y": "some string"
              }
            ]
      - name: Use outputs
        run: |
          echo "Output VAR_X: ${{ steps.get_vars.outputs.VAR_X }}"
          echo "Output VAR_Y: ${{ steps.get_vars.outputs.VAR_Y }}"
