name: "Use env"
on:
    workflow_dispatch:

jobs:
    use-env:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              with:
                envs: |
                    [
                        {
                            "branch": "demo"
                            "VAR_1": 123
                        },
                        {
                            "branch": "dev"
                            "VAR_X": "XXX"
                        },
                    ]
                    

                    
                    