name: "Use env"
on:
    workflow_dispatch:

jobs:
    use-env:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              with:
                envs: |
                    BRANCH=demo
                    VAR1=hello
                    VAR2=world
                    VAR_N=42

                    BRANCH=dev
                    VAR_X=xxx
                    VAR_Y=yyy

                    
                    