name: "Use env"
on:
  workflow_dispatch:

jobs:
  use-env:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Do some shelly stuff
        run: |
          echo "xxx=12" >> $GITHUB_ENV
          echo "aaa=Hello_World" >> $GITHUB_ENV
          echo "bbb=123-123-xxx-aaa" >> $GITHUB_ENV

          echo "$GITHUB_ENV"

      - name: Setup variables based on branch
        id: get_vars
        uses: ./use-env
        with:
          variables: |
            - branch: main
              VAR_X: PRODUCTION-STUFF
              VAR_Y: 123

            - branch: dev
              VAR_X: DEV-STUFF
              VAR_Y: 42

            - branch: demo
              VAR_X: DEMO-VAR
              VAR_Y: 99
      - name: Use outputs
        run: |
          echo "Output VAR_X: ${{ steps.get_vars.outputs.VAR_X }}"
          echo "Output VAR_Y: ${{ steps.get_vars.outputs.VAR_Y }}"
